service:
  name: openexchange-crawler

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-southeast-1

functions:
  crawl:
    handler: handler.crawl
    events:
      - http:
          method: post
          path: crawler
