service:
  name: openexchange-api

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

custom:
  custom:
  myStage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ${file(./config/config.js):config.AWS_REGION} 

functions:
  query:
    handler: handler.query
    events:
      - http:
          method: get
          path: query
