service:
  name: openexchange-api

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-southeast-1

functions:
  query:
    handler: handler.query
    events:
      - http:
          method: get
          path: query
